program = { statement } ;

statement = { expression };

# Expressions (higher have priority)
expression = add
add        = mul,     {S}, [ ('+' | '-'), {S}, mul ] ;
mul        = primary, {S}, { ('*' | '/' | '%'), {S}, primary } ;
primary    = terminal | '(' expression ')'


terminal = ident | number | string ;
ident    = alpha,  {alpha | digit | '_' | '-'} ;
number   = [ '-' ], digit, { digit };
string   = '"',    {any}, '"';
