program = { statement } ;

statement = { expression, [ ';' ] | assignation, [ ';' ] } ;

block = '{', { statement }, '}' ;
funcdef = iden, '::', '(', ')', block ;

assignation = 'let', S, ident, {S}, '=', {S}, expression;

# Expressions (lower have priority)
expression = equality
equality   = add,     {S}, [ ('<' | '>' | '==' | '!=' | '<=' | '>='), {S}, mul ] ; 
add        = mul,     {S}, [ ('+' | '-'), {S}, mul ] ;
mul        = primary, {S}, { ('*' | '/' | '%'), {S}, primary } ;
primary    = terminal | '(' expression ')' | funcall
funcall    = inden, {S}, '(' { expression } ')'


terminal = ident | number | string ;
ident    = alpha, { alpha | digit | '_' | '-' } ;
number   = [ '-' ], digit, { digit };
string   = '"',    {any}, '"';
