
main :: () {
    yop("bijour", 32);
    let y = {
        let c = 22;
    }
    bijour :: () {
        let a = 23;
        return {
            let b = 32;
            if (b < 30) {
                local reject;
            }
            local return b + a;
        }
    }
    let b = 23;
}

yop :: (
    hop: string,
    yop: i32,
) {
    let x = y(aled(b, hop), y * 52, hop(23));
    print(x, y, e);
}
